services:
  - type: web
    name: bprojetos
    env: node
    plan: free
    buildCommand: npm install && npm run build:render
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.16.11
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
