services:
  - type: web
    name: bprojetos
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
