services:
  - type: web
    name: bprojetos
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.16.11
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
